### ISSUE TITLE
Is the annotation file still available for downloading?

### ISSUE THREAD

**Issue by wangty1** [aakash4305/GBDF#4]
Hi, thanks for the brilliant work. As I am a bit late to find your work interesting, I could not find the annotation file GBDF_training_labels.xlsx on your GitHub page. Clicking the hyperlink of [releases](https://github.com/aakash4305/GBDF) guides me back to the home page of your GitHub page. I wonder if the annotation is still available for downloading. 

Thanks for your kind help in advance.

**Comment by aakash4305** [comment]
Hi Wangty1,

Thank you for your interest in our work. The annotations file is included in the releases. Please navigate to the releases section and select GBDF v1.0 to download the file GBDF_training_labels.xlsx. This file contains the labels along with corresponding file names and datasets. While we have the dataset, we cannot directly open-source it due to copyright restrictions; therefore, we have provided this file. I hope this is helpful.

Thank you!!

Regards,
Aakash

**Comment by aakash4305** [comment]
Hi Wangty1,

Thank you for your interest in our work. The annotations file is included in the releases. Please navigate to the releases section and select GBDF v1.0 to download the file GBDF_training_labels.xlsx. This file contains the labels along with corresponding file names and datasets. While we have the dataset, we cannot directly open-source it due to copyright restrictions; therefore, we have provided this file. I hope this is helpful.

Thank you!!

Regards,
Aakash
